<a href="https://colab.research.google.com/github/FelixEbenezer/Projet803_Mxnet/blob/main/Projet803_Mxnet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install mxnet

     |████████████████████████████████| 47.3 MB 1.7 MB/s 
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


# Quelques modules de framework Mxnet

# a) MXNET NDARAY

In [1]:
import mxnet as mx
from mxnet import nd

In [4]:
import mxnet as mx
# create a 1-dimensional array with a python list
a = mx.nd.array([1,2,3])
a


[1. 2. 3.]
<NDArray 3 @cpu(0)>

In [5]:
#avec numpy
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# create a 2-dimensional array with a nested python list
b = mx.nd.array([[1,2,3], [2,3,4]])
{'a.shape':a.shape, 'b.shape':b.shape}

{'a.shape': (3,), 'b.shape': (2, 3)}

In [7]:
b


[[1. 2. 3.]
 [2. 3. 4.]]
<NDArray 2x3 @cpu(0)>

Créer un NDArray sans aucune initialisation avec empty et full

In [8]:
x = nd.empty((3, 4))
print(x)
y = nd.full((3,4), 8)
print(y)


[[5.8826799e-08 3.0887421e-41 5.0446745e-44 0.0000000e+00]
 [          nan 0.0000000e+00 7.4091654e+28 5.2164852e-11]
 [7.5883790e+31 2.8969889e+23 1.8007912e+25 4.5448206e+30]]
<NDArray 3x4 @cpu(0)>

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
<NDArray 3x4 @cpu(0)>


Matrice de tous les zéros avec la fonction .zeros

In [9]:
x = nd.zeros((3, 8))
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
<NDArray 3x8 @cpu(0)>


In [10]:
#Matrice de tous les uns avec la fonction .ones
x = nd.ones((3, 8))
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 3x8 @cpu(0)>


In [11]:
#Création d'un tableau dont les valeurs sont échantillonnées au hasard
y = nd.random_normal(0, 1, shape=(3, 4))
print(y)


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>


In [12]:
#Trouver la dimension de chaque NDArray
y.shape

(3, 4)

In [13]:
# Trouver la taille de chaque NDArray
y.size

12

In [14]:
#Trouver le type de données de chaque NDArray
y.dtype

numpy.float32

Opérations NDArray
Dans cette section, nous vous présenterons les opérations de tableau de MXNet. NDArray prend en charge un grand nombre d'opérations mathématiques standard ainsi que des opérations sur place.

Opérations mathématiques standard

In [15]:
#Les opérations mathematiques sont faites element par element 
x = nd.ones((3, 5))
print(x)
y = nd.random_normal(0, 1, shape=(3, 5))
print(y)
print(x+y)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<NDArray 3x5 @cpu(0)>

[[ 0.2444218  -0.03716067 -0.48774993 -0.02261727  0.57461417]
 [ 1.4661262   0.6862904   0.35496104  1.0731696   0.12017461]
 [-0.9711102  -0.77569664 -0.7882176   0.7417728  -1.4734439 ]]
<NDArray 3x5 @cpu(0)>

[[ 1.2444218   0.9628393   0.51225007  0.9773827   1.5746142 ]
 [ 2.4661262   1.6862904   1.354961    2.0731697   1.1201746 ]
 [ 0.02888978  0.22430336  0.2117824   1.7417728  -0.47344387]]
<NDArray 3x5 @cpu(0)>


In [16]:
print(id(x))
print(id(y))

139916002060240
139916002060944


Contextes NDArray
Dans Apache MXNet, chaque tableau a un contexte et un contexte peut être le CPU, tandis que d'autres contextes peuvent être plusieurs GPU. Les choses peuvent devenir encore pires lorsque nous déployons le travail sur plusieurs serveurs. C'est pourquoi, nous devons assigner intelligemment les tableaux aux contextes. Cela minimisera le temps passé à transférer des données entre les appareils.

In [2]:
z = nd.ones(shape=(3,3), ctx=mx.cpu(0))
print(z)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>


In [18]:
#Nous pouvons copier le NDArray donné d'un contexte à un autre contexte en utilisant la méthode copyto() comme suit -
#on doit d activer le contexte gpu 
!pip install mxnet-cu101


     |████████████████████████████████| 358.1 MB 5.2 kB/s 


In [ ]:
#Et apres vous devez avoir activé au moins un GPU , une fois GPU activé, vous allez voir à la sortie de votre code au lieu que ce soit <NDArray 3x3 @cpu(0)>
#indiquant le contexte cpu, ça sera <NDArray 3x3 @gpu(0)>

In [3]:
x_gpu = z.copyto(mx.gpu(0))
print(x_gpu)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @gpu(0)>


Conversion de NDArray en NumPy Array
Apprenons comment pouvons-nous convertir NDArray en NumPy Array dans MXNet avec les fonctions .asnumpy() ou .asscalar()

Combiner un opérateur de niveau supérieur avec l'aide de quelques opérateurs de niveau inférieur

Parfois, nous pouvons assembler un opérateur de niveau supérieur en utilisant les opérateurs existants. L'un des meilleurs exemples de cela est l' opérateur np.full_like() , qui n'existe pas dans l'API NDArray. Il peut facilement être remplacé par une combinaison d'opérateurs existants comme suit :

In [4]:
from mxnet import nd
import numpy as np
np_x = np.full_like(a=np.arange(7, dtype=int), fill_value=15)
nd_x = nd.ones(shape=(7,)) * 15
np.array_equal(np_x, nd_x.asnumpy())

True

# Apache MXNet - API Python ndarray

a) FOnctions de classes et leurs parametres 

In [5]:
#Exemple de l utilisation de la fonction cast de l api ndarray de mxnet
nd.cast(nd.array([300, 10.1, 15.4, -1, -2]), dtype='uint8')


[ 44  10  15 255 254]
<NDArray 5 @cpu(0)>

In [ ]:
#Juste rappeler la sortie d un element ndarray: <NDArray 5 @cpu(0)>, il dit que l objet est de type ndarray, a 5 elements (shape) et est exécuté dans le contecxte cpu

b) fonctions de ndarray.contrib

In [ ]:
#Dans l'exemple ci-dessous, nous utiliserons la fonction while_loop pour exécuter une boucle while pour un calcul 
#défini par l'utilisateur et une condition de boucle :

In [7]:
cond = lambda i, s: i <= 7
func = lambda i, s: ([i + s], [i + 1, s + i])
loop_var = (mx.nd.array([0], dtype="int64"), mx.nd.array([1], dtype="int64"))
outputs, states = mx.nd.contrib.while_loop(cond, func, loop_var, max_iterations=10)
outputs

[
 [[             1]
  [             2]
  [             4]
  [             7]
  [            11]
  [            16]
  [            22]
  [            29]
  [94346013225408]
  [            32]]
 <NDArray 10x1 @cpu(0)>]

In [8]:
states

[
 [8]
 <NDArray 1 @cpu(0)>, 
 [29]
 <NDArray 1 @cpu(0)>]

c) ndarray.image
L'API Image NDArray est définie dans le package ndarray.image. Comme son nom l'indique, il est généralement utilisé pour les images et leurs caractéristiques.

In [9]:
#Exemple, nous utiliserons la fonction to_tensor pour convertir l'image NDArray de forme (H x W x C) ou (N x H x W x C) avec les 
#valeurs dans la plage [0, 255] en un tenseur NDArray de forme (C x H x W) ou (N x C x H x W) avec des valeurs dans la plage [0, 1].

import numpy as np
img = mx.nd.random.uniform(0, 255, (4, 2, 3)).astype(dtype=np.uint8)
mx.nd.image.to_tensor(img)


[[[0.54509807 0.84313726]
  [0.5411765  0.62352943]
  [0.43529412 0.05490196]
  [0.38039216 0.8117647 ]]

 [[0.5921569  0.6       ]
  [0.84705883 0.6431373 ]
  [0.29411766 0.9607843 ]
  [0.4745098  0.5254902 ]]

 [[0.7137255  0.85490197]
  [0.42352942 0.38431373]
  [0.8901961  0.27058825]
  [0.7882353  0.47843137]]]
<NDArray 3x4x2 @cpu(0)>

In [10]:
#un autre exemple avec la fonction normalize pour normaliser un tenseur de forme (C x H x W) ou (N x C x H x W) avec la moyenne et l'écart type (SD) .

img = mx.nd.random.uniform(0, 1, (3, 4, 2))

mx.nd.image.normalize(img, mean=(0, 1, 2), std=(3, 2, 1))


[[[ 0.18934818  0.13092826]
  [ 0.3085322   0.27869293]
  [ 0.02367868  0.11246539]
  [ 0.0290431   0.2160573 ]]

 [[-0.4898908  -0.31587923]
  [-0.08369008 -0.02142242]
  [-0.11092162 -0.42982462]
  [-0.06499392 -0.06495637]]

 [[-1.0213816  -1.526392  ]
  [-1.2008414  -1.1990893 ]
  [-1.5385206  -1.4795225 ]
  [-1.2194707  -1.3211205 ]]]
<NDArray 3x4x2 @cpu(0)>

d) ndarray.aléatoire

In [11]:
#Exemple1 avec la fonction uniforme, Dans l'exemple ci-dessous, nous allons tirer des échantillons aléatoires à partir d'une distribution uniforme. 
#Pour cela utilisera la fonction uniform() .

mx.nd.random.uniform(0, 1)


[0.11827442]
<NDArray 1 @cpu(0)>

In [12]:
low = mx.nd.array([1,2,3])
high = mx.nd.array([2,3,4])
mx.nd.random.uniform(low, high, shape=2)


[[1.7206327 1.639921 ]
 [2.5820198 2.1433532]
 [3.5373733 3.9446688]]
<NDArray 3x2 @cpu(0)>

In [ ]:
#Exemple2 avec la fonction generative_negative_binomial, Dans l'exemple ci-dessous, nous allons tirer des échantillons aléatoires à partir d'une distribution binomiale négative généralisée. Pour cela, nous utiliserons la fonction generalized_negative_binomial() .


In [13]:
mx.nd.random.generalized_negative_binomial(10, 0.5)


[9.]
<NDArray 1 @cpu(0)>

In [14]:
mu = mx.nd.array([1,2,3])
alpha = mx.nd.array([0.2,0.4,0.6])
mx.nd.random.generalized_negative_binomial(mu, alpha, shape=2)


[[0. 1.]
 [0. 0.]
 [2. 0.]]
<NDArray 3x2 @cpu(0)>

e) ndarray.utils

In [15]:
#Exemple, Dans l'exemple ci-dessous, nous allons retourner un nouveau tableau de forme et de type donnés, rempli de zéros. Pour cela, nous utiliserons la fonction zeros() .

mx.nd.zeros((1,2), mx.cpu(), stype='csr')


<CSRNDArray 1x2 @cpu(0)>

In [16]:
mx.nd.zeros((1,2), mx.cpu(), 'float16', stype='row_sparse').asnumpy()

array([[0., 0.]], dtype=float16)

In [ ]:
#Un autre exemple avec save et load

In [17]:
#Dans l'exemple ci-dessous, nous allons enregistrer une liste de tableaux et un dictionnaire de chaînes. Pour cela, nous utiliserons la fonction save() .
x = mx.nd.zeros((2,3))
y = mx.nd.ones((1,4))
mx.nd.save('list', [x,y])
mx.nd.save('dict', {'x':x, 'y':y})
mx.nd.load('list')

[
 [[0. 0. 0.]
  [0. 0. 0.]]
 <NDArray 2x3 @cpu(0)>, 
 [[1. 1. 1. 1.]]
 <NDArray 1x4 @cpu(0)>]

In [19]:
mx.nd.load('dict')

{'x': 
 [[0. 0. 0.]
  [0. 0. 0.]]
 <NDArray 2x3 @cpu(0)>, 'y': 
 [[1. 1. 1. 1.]]
 <NDArray 1x4 @cpu(0)>}

# Apache MXNet - Symbole API Python

In [22]:
#L'exemple ci-dessous montre comment on peut créer une expression simple en utilisant l'API Symbol de MXNet -

#Un NDArray en utilisant un 'tableau' 1-D et 2-D à partir d'une liste Python régulière -

import mxnet as mx
# Two placeholders namely x and y will be created with mx.sym.variable
x = mx.sym.Variable('x')
y = mx.sym.Variable('y')
# The symbol here is constructed using the plus ‘+’ operator.
z = x - y

In [23]:
z

<Symbol _minus0>

In [24]:
z = x + y
z

<Symbol _plus1>

In [25]:
(x, y, z)

(<Symbol x>, <Symbol y>, <Symbol _plus1>)

a) Ses fonctions de classes

In [26]:
#Exemples de mise en œuvre
#Dans l'exemple ci-dessous, nous utiliserons la fonction power() qui renverra le résultat élément par élément de l'élément de base élevé aux puissances de l'élément exp :

import mxnet as mx
mx.sym.power(3, 5)

243

In [27]:
#Exemple 2, Dans l'exemple ci-dessous, nous utiliserons la fonction SoftmaxActivation() (ou softmax()) qui sera appliquée en entrée et destinée aux couches internes.

input_data = mx.nd.array([[2., 0.9, -0.5, 4., 8.], [4., -.7, 9., 2., 0.9]])
soft_max_act = mx.nd.softmax(input_data)
print (soft_max_act.asnumpy())

[[2.4258138e-03 8.0748327e-04 1.9912291e-04 1.7924473e-02 9.7864312e-01]
 [6.6843736e-03 6.0796243e-05 9.9204904e-01 9.0463163e-04 3.0112558e-04]]


b) symbole.contrib

In [28]:
#Exemple, Dans l'exemple ci-dessous, nous utiliserons la fonction while_loop pour exécuter une boucle while pour un calcul défini par l'utilisateur et une condition de boucle -

cond = lambda i, s: i <= 7
func = lambda i, s: ([i + s], [i + 1, s + i])
loop_vars = (mx.sym.var('i'), mx.sym.var('s'))
outputs, states = mx.sym.contrib.while_loop(cond, func, loop_vars, max_iterations=10)
print(outputs)

[<Symbol _while_loop0>]


In [29]:
states

[<Symbol _while_loop0>, <Symbol _while_loop0>]

c) symbole.image

In [30]:
#Dans l'exemple ci-dessous, nous utiliserons la fonction to_tensor pour convertir l'image NDArray de forme (H x W x C) ou (N x H x W x C) avec les valeurs dans la plage [0, 255] en un tenseur NDArray de forme (C x H x W) ou (N x C x H x W) avec des valeurs dans la plage [0, 1].

import numpy as np

img = mx.sym.random.uniform(0, 255, (4, 2, 3)).astype(dtype=np.uint8)

mx.sym.image.to_tensor(img)

<Symbol to_tensor0>

In [31]:
#Exemple 2, Dans l'exemple ci-dessous, nous utiliserons la fonction normalize() pour normaliser un tenseur de forme (C x H x W) ou (N x C x H x W) avec moyenne et écart type (SD) .

img = mx.sym.random.uniform(0, 1, (3, 4, 2))

mx.sym.image.normalize(img, mean=(0, 1, 2), std=(3, 2, 1))

<Symbol normalize0>

d) symbole.sparse

# API Python Autograd et initialiseur

a) Classe fonction, methodes et leurs parametres

In [33]:
#Exemple, Dans l'exemple ci-dessous, nous utiliserons la méthode mxnet.autograd.grad() pour calculer le gradient de la tête par rapport aux variables -

x = mx.nd.ones((2,))
x.attach_grad()
with mx.autograd.record():
  z = mx.nd.elemwise_add(mx.nd.exp(x), x)
dx_grad = mx.autograd.grad(z, [x], create_graph=True)
dx_grad

[
 [3.7182817 3.7182817]
 <NDArray 2 @cpu(0)>]

mxnet.initializer
Il s'agit de l'API de MXNet pour l'initialiseur de pesée. Il a les classes suivantes -

In [35]:
#Dans l'exemple ci-dessous, nous utiliserons la classe mxnet.init.Normal() pour créer un initialiseur et récupérer ses paramètres -

init = mx.init.Normal(0.8)
init.dumps()

'["normal", {"sigma": 0.8}]'

In [36]:
#Exemple

init = mx.init.Xavier(factor_type="in", magnitude=2.45)
init.dumps()

'["xavier", {"rnd_type": "uniform", "factor_type": "in", "magnitude": 2.45}]'

In [ ]:
#Dans l'exemple ci-dessous, nous utiliserons la classe mxnet.initializer.Mixed() pour initialiser les paramètres à l'aide de plusieurs initialiseurs -

init = mx.initializer.Mixed(['bias', '.*'], [mx.init.Zero(),mx.init.Uniform(0.1)])
module.init_params(init)

for dictionary in module.get_params():
  for key in dictionary:
    print(key)
  print(dictionary[key].asnumpy())

# Apache MXNet - gluon de l'API Python

a) gluon nn

In [43]:
#Exemple 1
#Dans l'exemple ci-dessous, nous allons utiliser Block() qui donne la classe de base pour toutes les couches et modèles de réseau de neurones.

from mxnet.gluon import Block, nn
class Model(Block):
   def __init__(self, **kwargs):
      super(Model, self).__init__(**kwargs)
      # use name_scope to give child Blocks appropriate names.
      with self.name_scope():
         self.dense0 = nn.Dense(20)
         self.dense1 = nn.Dense(20)
   def forward(self, x):

      x = mx.nd.relu(self.dense0(x))
      return mx.nd.relu(self.dense1(x))

model = Model()
model.initialize(ctx=mx.cpu(0))
model(mx.nd.zeros((5, 5), ctx=mx.cpu(0)))


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<NDArray 5x20 @cpu(0)>

In [44]:
#Exemple 2
#Dans l'exemple ci-dessous, nous allons utiliser HybridBlock() qui prend en charge le transfert avec Symbol et NDArray.

import mxnet as mx
from mxnet.gluon import HybridBlock, nn


class Model(HybridBlock):
   def __init__(self, **kwargs):
      super(Model, self).__init__(**kwargs)
      # use name_scope to give child Blocks appropriate names.
      with self.name_scope():
         self.dense0 = nn.Dense(20)
         self.dense1 = nn.Dense(20)

   def forward(self, x):
      x = nd.relu(self.dense0(x))
      return nd.relu(self.dense1(x))
model = Model()
model.initialize(ctx=mx.cpu(0))

model.hybridize()
model(mx.nd.zeros((5, 5), ctx=mx.cpu(0)))


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<NDArray 5x20 @cpu(0)>

b) gluon.rnn

In [45]:
#Exemple 1
#Dans l'exemple ci-dessous, nous allons utiliser GRU () qui applique une unité récurrente multicouche (GRU) RNN à une séquence d'entrée donnée.

layer = mx.gluon.rnn.GRU(100, 3)
layer.initialize()
input_seq = mx.nd.random.uniform(shape=(5, 3, 10))
out_seq = layer(input_seq)
h0 = mx.nd.random.uniform(shape=(3, 3, 100))
out_seq, hn = layer(input_seq, h0)
out_seq


[[[ 8.82510692e-02  5.98370492e-01  8.78963619e-02 ...  4.52250570e-01
    1.43120617e-01  8.14713910e-03]
  [ 3.30856025e-01  1.22884169e-01  1.80029064e-01 ...  6.94054365e-02
   -6.30930066e-03  1.88858539e-01]
  [ 2.22866923e-01  3.64539683e-01  2.24259242e-01 ...  2.24734128e-01
    3.41983467e-01  1.48379773e-01]]

 [[ 7.13944137e-02  3.77085567e-01  3.88878845e-02 ...  2.56424963e-01
    7.97149613e-02 -3.84403626e-03]
  [ 1.34998485e-01  9.95739549e-02  1.24262735e-01 ...  3.39990407e-02
   -2.23748386e-02  1.49599701e-01]
  [ 1.09922804e-01  2.23233327e-01  1.37406603e-01 ...  1.07579812e-01
    1.61547467e-01  1.12562105e-01]]

 [[ 5.13373576e-02  2.21865490e-01  1.79146696e-02 ...  1.51024505e-01
    3.98351811e-02 -3.55580682e-03]
  [ 4.93958890e-02  6.43125549e-02  7.85289407e-02 ...  2.48136334e-02
   -2.14191563e-02  1.03798047e-01]
  [ 5.83099909e-02  1.28322393e-01  8.36149082e-02 ...  5.39119765e-02
    7.48012140e-02  7.94764310e-02]]

 [[ 3.60381380e-02  1.25775546

In [46]:
#Exemple 2
#Dans l'exemple ci-dessous, nous allons utiliser LSTM () qui applique un RNN de mémoire à long terme (LSTM) à une séquence d'entrée donnée.

layer = mx.gluon.rnn.LSTM(100, 3)
layer.initialize()

input_seq = mx.nd.random.uniform(shape=(5, 3, 10))
out_seq = layer(input_seq)
h0 = mx.nd.random.uniform(shape=(3, 3, 100))
c0 = mx.nd.random.uniform(shape=(3, 3, 100))
out_seq, hn = layer(input_seq,[h0,c0])
out_seq


[[[ 9.88702476e-02  2.92791110e-02  1.73070654e-01 ...  5.00726998e-02
    1.20640792e-01  2.03052074e-01]
  [ 1.55304536e-01 -4.65283394e-02  1.75588176e-01 ...  1.88295797e-01
    2.32254624e-01  3.05395070e-02]
  [ 8.49643722e-02  1.01938546e-02  1.08178757e-01 ...  9.99166518e-02
    1.29304871e-01  7.53594562e-02]]

 [[ 5.82398102e-02  4.89533320e-03  9.34099928e-02 ...  1.85772665e-02
    4.64612469e-02  8.53038952e-02]
  [ 8.28957632e-02 -2.55741980e-02  9.37088430e-02 ...  1.16543531e-01
    1.00412995e-01  2.63477750e-02]
  [ 4.81191166e-02  3.00772581e-03  5.53560704e-02 ...  6.24521002e-02
    6.12978153e-02  4.68443856e-02]]

 [[ 3.48323658e-02 -1.28835475e-03  5.30818999e-02 ...  5.76857850e-03
    1.55930026e-02  3.53714600e-02]
  [ 4.34247106e-02 -1.82160120e-02  4.76683713e-02 ...  6.17266335e-02
    4.95757461e-02  1.83805153e-02]
  [ 2.68392172e-02  1.15902536e-03  3.17772143e-02 ...  3.38127725e-02
    2.91226488e-02  2.55632140e-02]]

 [[ 2.06502955e-02 -1.86687021

Modules de formation
Les modules de formation à Gluon sont les suivants −

perte de gluon

In [47]:
#Exemple 1
#Dans l'exemple ci-dessous, nous allons initialiser les paramètres et les tableaux de dégradés en utilisant la méthode initialize() comme suit -

weight = mx.gluon.Parameter('weight', shape=(2, 2))
weight.initialize(ctx=mx.cpu(0))
weight.data()


[[-0.03063859 -0.02505398]
 [ 0.02994981 -0.06580696]]
<NDArray 2x2 @cpu(0)>

In [48]:
weight.grad()


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

c) gluon.data

In [50]:
#Exemple1
#Dans l'exemple ci-dessous, nous allons utiliser l'API gluon.data.BatchSampler() , qui enveloppe un autre échantillonneur. Il renvoie les mini lots d'échantillons.

import mxnet as mx
from mxnet.gluon import data
sampler = mx.gluon.data.SequentialSampler(15)
batch_sampler = mx.gluon.data.BatchSampler(sampler, 4, 'keep')
list(batch_sampler)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14]]